@startuml
start
split
    :カレンダーを調べて
    誕生日を入手;
    :パソコンのパスワードを解除;
split again
    :水道の水を抜いて
    棚の鍵を入手;
    :延長コード、USBを入手;
    :延長コードでプロジェクターの
    電源をON;

split again
    :ゴミ箱からフィルムを入手;
split again
    :机から本を入手;
    :本棚に入れる
    WBの謎解きのヒントを入手;
    :WBから電子ロックボックスの
    暗証番号を入手;
    :棚の鍵を入手;
    :棚からハサミ、インクを入手;
end split
stop
@enduml
