@startuml
start
    repeat
        split
            :カレンダーを調べて
            誕生日を入手;
            :パソコンのパスワードを解除;
        split again
            :水道の水を抜いて
            棚の鍵を入手;
            :延長コード、USBを入手;
            if(延長コードを選択状態) then (yes)
                :延長コードでプロジェクターの
                電源をON;
            endif

        split again
            :ゴミ箱からフィルムを入手;
        split again
            :机から本を入手;
            :本棚に入れる
            WBの謎解きのヒントを入手;
            :WBから電子ロックボックスの
            暗証番号を入手;
            :棚の鍵を入手;
            if(棚の鍵を選択状態) then (yes)
                :棚からハサミ、インクを入手;
            endif
        split again
            :長い棒を入手;
            if(長い棒を選択状態) then (yes)
                :スクリーンを下ろす;
            endif
        end split

        if (パソコン起動 and usbを選択状態) then (yes)
            :usbをパソコンに挿入;
        endif
        if(usbをパソコンに挿入済み and \nプリンターにインクが挿入済み) then (yes)
            :パソコンから印刷指示;
        endif
        if(紙を入手 and ハサミを選択状態) then (yes)
            :フィルムを入手;
        endif

        if(フィルムを選択状態 and プロジェクターの電源ON) then (yes)
            :フィルムを重ねる。;
        endif 
        if(プロジェクターに2枚のフィルムが重なっている。) then (yes)
            :キーボックスの暗証番号を入手;
            :キーボックスを解錠;
            :ドアの鍵を入手;
            if(ドアの鍵を選択状態) then (yes)
                :ドアを開ける;
                stop
            endif 


@enduml
